In [ ]:
import pandas as pd

def read_csv_to_dataframe(file_path):
   """
   Reads a CSV file and returns a pandas DataFrame.
   
   Args:
      file_path (str): The path to the CSV file.
   
   Returns:
      pd.DataFrame: A DataFrame containing the data from the CSV file.
   """
   try:
      df = pd.read_csv(file_path)
      return df
   except Exception as e:
      print(f"Error reading CSV file: {e}")
      return None

In [5]:
df = read_csv_to_dataframe('../data/dataset/entry_data.csv')

df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
1,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
2,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
3,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62
4,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,CA-2015-115259,25/08/2015,27/08/2015,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,Ohio,43229,East,OFF-EN-10002600,Office Supplies,Envelopes,"Redi-Strip #10 Envelopes, 4 1/8 x 9 1/2",4.72
116,116,CA-2015-115259,25/08/2015,27/08/2015,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,Ohio,43229,East,OFF-PA-10004965,Office Supplies,Paper,Xerox 1921,23.976
117,117,CA-2015-115259,25/08/2015,27/08/2015,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,Ohio,43229,East,OFF-EN-10002504,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Plai...",130.464
118,118,CA-2016-110457,02/03/2016,06/03/2016,Standard Class,DK-13090,Dave Kipp,Consumer,United States,Seattle,Washington,98103,West,FUR-TA-10001768,Furniture,Tables,Hon Racetrack Conference Tables,787.53
119,119,US-2016-136476,05/04/2016,10/04/2016,Standard Class,GG-14650,Greg Guthrie,Corporate,United States,Bristol,Tennessee,37620,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,157.794

In [6]:
df_cleaned = df.dropna()
df_cleaned

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
1,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
2,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
3,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62
4,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,CA-2015-115259,25/08/2015,27/08/2015,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,Ohio,43229,East,OFF-EN-10002600,Office Supplies,Envelopes,"Redi-Strip #10 Envelopes, 4 1/8 x 9 1/2",4.72
116,116,CA-2015-115259,25/08/2015,27/08/2015,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,Ohio,43229,East,OFF-PA-10004965,Office Supplies,Paper,Xerox 1921,23.976
117,117,CA-2015-115259,25/08/2015,27/08/2015,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,Ohio,43229,East,OFF-EN-10002504,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Plai...",130.464
118,118,CA-2016-110457,02/03/2016,06/03/2016,Standard Class,DK-13090,Dave Kipp,Consumer,United States,Seattle,Washington,98103,West,FUR-TA-10001768,Furniture,Tables,Hon Racetrack Conference Tables,787.53
119,119,US-2016-136476,05/04/2016,10/04/2016,Standard Class,GG-14650,Greg Guthrie,Corporate,United States,Bristol,Tennessee,37620,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,157.794